### ISSUE TITLE
`x-oapi-codegen-extra-tags` is valid for queries but not for paths

### ISSUE THREAD

**Issue by intercept6** [deepmap/oapi-codegen#1028]
If you define it this way for a query, the tag will be added, but not for a path.

### query

```yaml
  /pets:
    get:
      summary: Returns all pets
      operationId: findPets
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
          x-oapi-codegen-extra-tags:
            validate: "required"
```
```golang
type FindPetsRequestObject struct {
	Params FindPetsParams
}
type FindPetsParams struct {
	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty" validate:"required"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}
```

### path

```yaml
  /pets/{id}:
    get:
      summary: Returns a pet by ID
      description: Returns a pet based on a single ID
      operationId: findPetByID
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
          x-oapi-codegen-extra-tags:
            validate: required,uuid
```
```golang
type FindPetByIDRequestObject struct {
	Id int64 `json:"id"`
}
```
