### ISSUE TITLE
Failing generation (formatting) if there are special characters in names

### ISSUE THREAD

**Issue by daolis** [deepmap/oapi-codegen#105]
Example:
```
  parameters:
    Count:
      name: $count
      in: query
      schema:
        type: boolean
```
Generator uses $count as go variable name and this is not compiling...
