### ISSUE TITLE
Code does not check for nil values

### ISSUE THREAD

**Issue by yuoppp** [deepmap/oapi-codegen#1062]
openapi spec:
```
/1/values/:
  get:
    operationId: getValues
    parameters:
      -  in: query
         name: lang
         schema:
           type: string
         enum:
           - fr
           - en
         default: en
```

generates the following code:
```
func NewSuggestTVMRequestWithBody(server string, params *GetValuesParams, contentType string, body io.Reader) (*http.Request, error) {
    ...
    
    if params.Lang != nil {
    }
}
```

which causes panic `invalid memory address or nil pointer dereference`

it should be checked for nil
