### ISSUE TITLE
`user-templates` not working?

### ISSUE THREAD

**Issue by amweiss** [deepmap/oapi-codegen#1070]
I have a config that looks like:
```yaml
generate:
  models: true
  gin-server: true
  embedded-spec: true
  strict-server: true
output-options:
  skip-fmt: true
  user-templates:
   gin/gin-wrappers.tmpl: api/rest/openapi/templates/gin/gin-wrappers.tmpl
```

`skip-fmt` is used to show the error rather than just fail.

Where `api/rest/....` is relative to the repo root, and then I run:
`oapi-codegen -config api/rest/openapi/openapi-gen-config.yaml -package spec -o api/rest/spec/spec.gen.go api/rest/openapi/spec.yaml`

The generated output looks like this:
```go
...
}

api/rest/openapi/templates/gin/gin-wrappers.tmpl
// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
    BaseURL string
    Middlewares []MiddlewareFunc
    ErrorHandler func(*gin.Context, error, int)
}
...
```

Where the file name is just inserted into the code rather than the parsed file contents. Am I doing something wrong or is this not supported?
