### ISSUE TITLE
Cannot disable server name validation if the servers array includes a base path.

### ISSUE THREAD

**Issue by codestation** [deepmap/oapi-codegen#1123]
According to #882 , setting `swagger.Servers = nil` skips the server name matching, but the problem is if for example one has a base path in the server url entry (for example the petstore) it causes that all the routes return `no matching operation was found`.

In my case this my server array and a path:

```yaml
servers:
  - url: 'http://localhost:8000/apis/myapp/v1'
paths:
  "/health/live":
  ...
```

Calling `http://localhost:8000/apis/myapp/v1/health/live` fails if Servers is nil. I tried to debug and found that it tries to match `/apis/myapp/v1/health/live` (the request) with `^/health/live$` (the route).

Maybe doing `Servers = nil` is a bad idea as it drops critical information (the base path), so another way should be implemented.
