### ISSUE TITLE
bug: generated server code for chi is not working

### ISSUE THREAD

**Issue by sarathsp06** [deepmap/oapi-codegen#1130]
When the response is of type `text/plain` generated server code is trying to convert to []byte while the response object is a struct 
```yml
ForbiddenError:
      description: Access token is valid but does not have the required scope
      content:
        text/plain:
          schema:
            type: string
            example: Forbidden
```
generated code
```go
type GetAccounts403TextResponse struct{ ForbiddenErrorTextResponse }

func (response GetAccounts403TextResponse) VisitGetAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(403)

	_, err := w.Write([]byte(response))
	return err
}

```

`_, err := w.Write([]byte(response))` fails at compile time
