### ISSUE TITLE
Object query parameters not styled

### ISSUE THREAD

**Issue by MrWako** [deepmap/oapi-codegen#115]
I've been enjoying using this new library for client & server OpenAPI 3 codegen. One small glitch I came across is that if you define an object in the query, for example
```
- name: filter
  in: query
  required: false
  style: deepObject
  explode: true
  schema:
    type: object
```
then using the generated client fails at run time because the `map[string]interface{}` object cannot currently be styled.

I'll get a suggested pull request together with the fix.
