### ISSUE TITLE
multipart/form-data - value must be an object

### ISSUE THREAD

**Issue by Ol1BoT** [deepmap/oapi-codegen#1169]
version: `v1.13.0`

When I POST a multipart/form I get the following:

`code=400, message=request body has an error: doesn't match schema: value must be an object, internal=request body has an error: doesn't match schema: value must be an object`

I've clipped off the rest for brevity.

The yaml looks as follows:

```yaml
  /api/v1/upload/{id}:
    post:
      operationId: FileUpload
      x-requires-permission: user:write
      parameters:
        in: path
        name: id
        schema:
          type: string
        required: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

and the cURL command i'm using is

```cURL
curl --request POST \
  --url https://site.com/api/v1/upload/<id> \
  --header 'Authorization: Bearer <token>' \
  --header 'Content-Type: multipart/form-data' \
  --form file=@/uploads/to_upload.zip
```
[I seem to be following the openapi spec to a T](https://swagger.io/docs/specification/describing-request-body/multipart-requests/), I also added in the following:

```Go
openapi3filter.RegisterBodyDecoder("application/zip", openapi3filter.FileBodyDecoder)
openapi3filter.RegisterBodyDecoder("multipart/form-data", openapi3filter.FileBodyDecoder)
```

I don't think the `application/zip` is necessary but I've included it anyway.

I've been using https://github.com/deepmap/oapi-codegen/issues/514 as a reference but I've seem to run out of things to try.

**Comment by Ol1BoT** [comment]
removing the `middleware.OapiRequestValidator(swaggerSpec)` "fixes" the issue.

Is it something I'm doing incorrectly or should I investigate why the middleware isn't considering this a valid object?

**Comment by Ol1BoT** [comment]
issue with kin-openapi, closing.

**Comment by lukasbash** [comment]
I am facing the same problem. Can you elaborate a bit how kin-openapi is connected to this issue? Also, skipping the validation is not really an option for me.

Is there something I can change without skipping the validator?

**Comment by Ol1BoT** [comment]
@lukasbash 
Delete `openapi3filter.RegisterBodyDecoder("multipart/form-data", openapi3filter.FileBodyDecoder)`

**Comment by lukasbash** [comment]
@Ol1BoT 
I already removed this line. Without the following code
```go
			Skipper: func(ctx echo.Context) bool {
				cts := ctx.Request().Header["Content-Type"]

				return lo.SomeBy(cts, func(ct string) bool {
					return strings.Contains(ct, "multipart/form-data")
				})
			},
```

I get an error `request body has an error: failed to decode request body: path file: unsupported content type \"image/png\"`

This is my API requestBody content:
```yaml
          multipart/form-data:
            schema:
              type: object
              required:
                - "file"
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/png, image/jpeg
```
