### ISSUE TITLE
Skip optional pointer dont work with x-go-type

### ISSUE THREAD

**Issue by Amf1k** [deepmap/oapi-codegen#1195]
I want to use `x-go-type` and `x-go-type-skip-optional-pointer` for change my optional type to null type.
For example
```
    AuthResponse:
      type: object
      required:
        - user_phone
      properties:
        auth_hash:
          type: string
          x-go-type: null.String
          x-go-type-skip-optional-pointer: true
        user_phone:
          type: string
          pattern: ^\+(\d){5,25}$
          format: phone
          description: Phone number
```
i expect to see
```
type AuthResponse struct {
	AuthHash null.String `json:"auth_hash"`
	UserPhone string `json:"user_phone"`
}
```

but I get
```
type AuthResponse struct {
	AuthHash *null.String `json:"auth_hash"`
	UserPhone string `json:"user_phone"`
}
```
