### ISSUE TITLE
is there a verbose mode to diagnose errors?

### ISSUE THREAD

**Issue by tommyjcarpenter** [deepmap/oapi-codegen#1261]
Is there a verbose flag or a way to see line numbers/more info/etc for generation failures?

eg
```
oapi-codegen -package indexapi apis/openapi_resolved.yaml > indexapi.gen.go     

error loading swagger spec in apis/openapi_resolved.yaml
: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field TBis.components of type bool⏎
```

it's hard for me to really fix or diagnose this from a 4000 line openapi.yaml from that alone

**Comment by filinvadim** [comment]
Got the same error:
`error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field TBis.components of type openapi3.SchemaBismake`

**Comment by bernii** [comment]
@tommyjcarpenter were you able to figure this out? having the same issue

**Comment by tommyjcarpenter** [comment]
@bernii yes, although not using this package directly. 

I;
1  loaded up the openapi.yaml in the swagger error and fixed all the warnings I could
2 Added back one endpoint at a time, until I found the offending block

I forget what the actual issue was but it was something very simple like float/number

I DO still think a verbose generation mode, if possible, would be a huge help

**Comment by bruno-nascimento** [comment]
I had the same problem and found this issue.

In my case, the @tommyjcarpenter tip helped me see that I was putting the required: attribute in the wrong place.

I went to [https://editor.swagger.io/,](https://editor.swagger.io/) added my spec and got all my errors highlighted :)

how it was:
```yaml
    NewTranslation:
      properties:
        word:
          type: string
          description: The word to be translated
          required: true
        language:
          type: string
          description: The language of the word to be translated
          required: true
        translation:
          type: string
          description: The translation of the word
          required: true
```


how it should be:
``` yaml
    NewTranslation:
      required: 
      - word
      - language
      - translation
      properties:
        word:
          type: string
          description: The word to be translated
        language:
          type: string
          description: The language of the word to be translated
        translation:
          type: string
          description: The translation of the word
```
