### ISSUE TITLE
Wrong type when using x-go-type-skip-optional-pointer

### ISSUE THREAD

**Issue by sonu27** [deepmap/oapi-codegen#1263]
When using `x-go-type-skip-optional-pointer` on an optional header, invalid code gets generated which cannot compile.

```yaml
openapi: 3.0.3
info:
  title: Form API
  version: '1.0'
paths:
  /api/v1/forms/contact:
    post:
      operationId: sendContactForm
      parameters:
        - in: header
          name: X-Real-IP
          required: false
          schema:
            type: string
            x-go-type-skip-optional-pointer: true # the problem
      responses:
        '204':
          description: Contact form sent
      tags:
        - form

```

This results in:
```go
// ------------- Optional header parameter "X-Real-IP" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Real-IP")]; found {
		var XRealIP string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Real-IP", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Real-IP", runtime.ParamLocationHeader, valueList[0], &XRealIP)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Real-IP", Err: err})
			return
		}

		params.XRealIP = &XRealIP // the problem, should be without the pointer
		// the fix: params.XRealIP = XRealIP

	}
```

**Comment by marcomayer** [comment]
Stumbled into the same issue with:

```
        - name: pct
          in: query
          required: false
          schema:
            type: integer
            default: 0
            x-go-type-skip-optional-pointer: true
            minimum: 0
            maximum: 100

```
Code:
`	err = runtime.BindQueryParameter("form", true, false, "pct", r.URL.Query(), &params.Pct)`

Getting:
`panic: reflect: call of reflect.Value.IsNil on int Value
`
Maybe I misunderstood how/when x-go-type-skip-optional-pointer should be used?
