### ISSUE TITLE
Recommended way of overriding JSON marshaler utilized by generated schema handlers

### ISSUE THREAD

**Issue by alecholmez** [deepmap/oapi-codegen#1319]
I have a use case that requires I swap out the stock `encoding/json` lib for certain objects. Particularly to something like `protojson`.

What is the recommended way of doing this? If it's not possible I can certainly script around this but was curious if theres a first-party mechanism of change.

**Comment by alecholmez** [comment]
Side note, I noticed that if you have oneOf specs with various objects, certain properties don't generate and the go is invalid. Ex:

```yaml
oneOf:
        - type: object
          properties:
            data: 
              type: object
              description: random data
              additionalProperties: true
        - type: object
          properties:
            upgrades:
              type: string
              enum:
                - my_thing
```
The enum under `upgrades` never gets generated.
