### ISSUE TITLE
OpenAPI query param setting `allowReserved` is not supported

### ISSUE THREAD

**Issue by stefanmeschke** [deepmap/oapi-codegen#1342]
### Issue

When defining a query parameter with `allowReserved: true` the query parameter will be encoded as well.

### Example

```
  /rest/organizations:
    get:
      …
      parameters:
        - name: ids
          description: |
            Organization IDs as comma separated list in List(…) format.
            It is important that this parameter is not URL encoded.
          in: query
          example: List(79988552,27056405)
          schema:
            type: string
          required: true
          allowReserved: true
```

### Actual

`rest/organizations?ids=List%2879988552,27056405%29`

### Expected

`rest/organizations?ids=List(79988552,27056405)`

### Notes

I know this is not a proper API design. Unfortunately this is a third party api which we have to use.
