### ISSUE TITLE
x-go-type-skip-optional-pointer not working

### ISSUE THREAD

**Issue by djdylan2000** [deepmap/oapi-codegen#1422]
Code gen version: `v1.16.2`
generation commands:
```
//go:generate oapi-codegen --package=openapi -generate=types -import-mapping=./common-types.yaml:github.com/mycompany/myproject/api/v1/gen,./enums.yaml:github.com/mycompany/myproject/internal/common/enums -o ./gen/mydomain/heat_pumps_openapi_types.go ./openapi-spec/myspec.yaml
//go:generate oapi-codegen --package=openapi -generate=strict-server,gin -import-mapping=./common-types.yaml:github.com/mycompany/myproject/api/v1/gen,./enums.yaml:github.com/mycompany/myproject/internal/common/enums -o ./gen/mydomain/myspec_openapi_server.go ./openapi-spec/myspec.yaml
//go:generate oapi-codegen --package=openapi -generate=spec -import-mapping=./common-types.yaml:github.com/mycompany/myproject/api/v1/gen,./enums.yaml:github.com/mycompany/myproject/internal/common/enums -o ./gen/mydomain/myspec_openapi_spec.go ./openapi-spec/myspec.yaml
```

OpenAPI definition in YAML:
```
components:
  schemas:
    MyPatchV1Request:
      type: object
      properties:
        templateId:
          type: string
          x-go-type-skip-optional-pointer: true
```

Generated code
```
// MyPatchV1Request defines model for MyPatchV1Request.
type MyPatchV1Request struct {
  TemplateId *string `json:"templateId,omitempty"`
}
```

According to the documentation, TemplateId should not be a pointer due to `x-go-type-skip-optional-pointer: true`, but it appears to not be working as documented.

**Comment by austincollinpena** [comment]
Adding it under `tag` worked for me:

```yaml
    HelloPostRequest:
      required:
        - name
      properties:
        name:
          type: string
          description: The name of the person to greet
        tag:
          type: string
          x-go-type-skip-optional-pointer: true
          description: The tag to use for the greeting
```
