### ISSUE TITLE
Validation of type formats (e.g. email) for Query Parameters

### ISSUE THREAD

**Issue by sonic-martin** [deepmap/oapi-codegen#1517]
Currently type formats in OAS, like in the example below, seems only to be supported by oapi-codegen in case of usage in JSON data, e.g. in request bodies. But from my understanding `format: email` is also allowed in (query) parameters, e.g. in a HEAD or GET request.

Am I correct?

And would it be in scope of oapi-codegen to also validate format-hints in parameters?

```yaml
...
      name: mail
      in: query
      required: true
      allowEmptyValue: false
      schema:
        type: string
        format: email
```
