### ISSUE TITLE
OAS 'date-time' type in query parameter causes panic in client

### ISSUE THREAD

**Issue by joonashaapsaari** [deepmap/oapi-codegen#153]
Using time (date-time) parameter in client causes the following panic when the parameter is set:

`panic: reflect.Value.Interface: cannot return value obtained from unexported field or method`

Example OAS spec:
```
paths:
  /test:
    description: Test API
    get:
      tags:
        - test
      summary: Get Test
      operationId: GetTest
      parameters:
        - in: query
          description: Timestamp
          name: ts
          schema:
            type: string
            format: 'date-time'
            description: Timestamp
```

Suggested fix in PR
#152
