### ISSUE TITLE
Add support for generating only whitelisted schemas

### ISSUE THREAD

**Issue by ramizpolic** [deepmap/oapi-codegen#1540]
## Overview

As a user, I would like to generate only specific schemas (mainly when generating models).
The new flag would generate models similar to `--exclude-schemas`, but via whitelisting approach rather than blacklisting.
The reason for that is that schema generation via `--exclude-schemas` is not usable for large OpenAPI specs.

## Implementation
It should only work when generating models from OpenAPI specs. The new flag/option could be defined as `--only-schemas` (or some alternative name). For validation, if both `--only-schemas` and ` --exclude-schemas` are passed, an error would be raised.

## Example
OpenAPI specs
```yaml
---
  schemas:
    Book:
      properties:
        name:
          type: string

    Article:
      properties:
        name:
          type: string

    Ignored:
      properties:
        name:
          type: string
```

Model generator config
```yaml
---
package: models
output: models/models.gen.go
generate:
  models: true
only-schemas:
	- Book
	- Article
```

## Use-case
Generating modules for sub-components/SDKs from a parent OpenAPI specs. For example, when we need only some models defined in a central OpenAPI specs, we would use the `--only-schemas` flag/option.
