### ISSUE TITLE
Is there a way to customize the json tag names?

### ISSUE THREAD

**Issue by deitch** [deepmap/oapi-codegen#1602]
E.g. if I have a basic spec like:

```yaml
components:
   schemas:
     Foo:
       type: object
       properties:
         id:
           type: string
         size:
           type: integer
```

that will convert into the following:

```go
type Foo struct {
	ID   *string `json:"id,omitempty"`
	Size *int `json:"size,omitempty"`
}
```

I can use `name-normalizer` to change how the struct field is named, but what if I want to change the json property name? Is there a type of processor I can give it, or does one of the modification tags like `x-oapi-*` do that?

Ideally, I am thinking of something in the spirit of name-normalizer, where it is some arbitrary code that has logic to it, as opposed to a tag on each and every field (which can get tedious). But even tags would be a start.

Somewhat loosely related to #849
