### ISSUE TITLE
Remove common path from generated function names

### ISSUE THREAD

**Issue by jacksgt** [deepmap/oapi-codegen#1613]
Hello,

I have an OpenAPI spec that has a bunch of endpoints like this:

```json
  "paths": {
    "/api/v1.0/Application/{id}": {
      "post": { ... }
      "get": { ... }
    "/api/v1.0/Application/{id}/providers": {
      "get": { ... }
   }
}
```

And a basic config:

```yaml
package: authzApiClient
output: internal/authzApiClient/v1/client.gen.go
generate:
  models: true
  client: true
compatibility:
  circular-reference-limit: 10
output-options:
  include-tags:
    - Application
```

Subsequently the generated client methods look like this:

```go
type ClientInterface interface {
	// GetApiV10Application request
	GetApiV10Application(ctx context.Context, params *GetApiV10ApplicationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV10ApplicationWithBody request with any body
	PostApiV10ApplicationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

        // GetApiV10ApplicationIdProviders request
	GetApiV10ApplicationIdProviders(ctx context.Context, params *GetApiV10ApplicationIdProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error)
 ...
}
```

Is it possible to remove the common `/api/v1.0/` / `ApiV10` prefix from the generated function and struct names?
I looked into [name-normalizers](https://github.com/deepmap/oapi-codegen?tab=readme-ov-file#changing-the-names-of-generated-types), but that doesn't seem to apply here.

Thanks!
