### ISSUE TITLE
Bug: Header parameter parsing with fiber generator

### ISSUE THREAD

**Issue by dani3lsf** [deepmap/oapi-codegen#1621]
The fiber server generator is not able to handle header parameters correctly. For example, having the following configuration:
```
post:
  description: 'ExecuteOrders'
  operationId: ExecuteOrders
  security:
    - BearerAuth:
      - admin
  parameters:
    - name: "X-Idempotency-Key"
      in: header
      description: The idempotency key
      required: false
      schema:
        type: string
```

The generated code is for the parsing of the header is:
![image](https://github.com/deepmap/oapi-codegen/assets/36214281/00de00e5-4286-42ea-8a2b-447f78dfcf32)
 
The compiler throws the following error: 
`cannot use value (variable of type []string) as string value in argument to runtime.BindStyledParameterWithOptions`
as  the variable "value" from headers is of type []string meanwhile the method BindStyledParameterWithOptions expects a string.

This is not a problem for example with the echo-server where the generator gets the first string of the list:
![image](https://github.com/deepmap/oapi-codegen/assets/36214281/a06c398f-0c9e-4861-b2f0-f1bcfcb5e7e3)
