### ISSUE TITLE
swaggerSpec updated even when no spec changes

### ISSUE THREAD

**Issue by rim-zahir** [deepmap/oapi-codegen#1623]
Hello,

I am facing an issue where running the generate task systematically results in the `swaggerSpec` being updated even no yaml spec changes have been issued. 
I suspect it is to do with the `import-mapping` ordering that is non deterministic but I'm not 100% sure.

My generate yml config looks like the following :
```
package: dummy
generate:
  models: true
  gorilla-server: true
  strict-server: true
  embedded-spec: true
output-options:
  skip-prune: true
import-mapping:
  schemas/object_1.yml: github.com/object_1
  schemas/object_2.yml: github.com/object_2
```

I suspect the order between the `object_1` and `object_2` mappings are interchangeable at code generation type and that's what being detected as an update.

I had a look around the codebase (new to it so apologies in advance if I misunderstood something) but I'm wondering if the issue comes from the import map not being key ordered in this [snippet](https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/codegen.go#L78)

Let me know your thoughts. 
Thanks for the help
