### ISSUE TITLE
Support two dimensional query parameters

### ISSUE THREAD

**Issue by renom** [deepmap/oapi-codegen#1631]
Let's say we have a query parameter in the openapi spec:
```yaml
- name: param
  in: query
  explode: true
  pipeDelimited: true
  schema:
    type: array
    items:
      type: array
      items:
        type: string
```
And the generated code for this param:
```go
type GetItemsParamsParam string

type GetItemsParams struct {
	Param *[][]GetItemsParamsParam `form:"param,omitempty" json:"param,omitempty"`
}
```
Then the following request params:
```http
GET http://localhost/items?param=value1|value2&param=value3|value4|value5 HTTP/1.1
```
Will be transformed into:
```
(api.GetItemsParams) {
 Param: (*[][]api.GetItemsParamsParam)(0xc00074a330)((len=2 cap=2) {
  ([]api.GetItemsParamsParam) (len=2 cap=2) {
   (api.GetItemsParamsParam) (len=6) "value1",
   (api.GetItemsParamsParam) (len=6) "value2"
  },
  ([]api.GetItemsParamsParam) (len=3 cap=3) {
   (api.GetItemsParamsParam) (len=6) "value3",
   (api.GetItemsParamsParam) (len=6) "value4",
   (api.GetItemsParamsParam) (len=6) "value5"
  }
 })
}
```

I'm not sure whether OpenAPI Specification implies it to work that way or not, but at least it'd be helpful in some cases.
