### ISSUE TITLE
Nullable values

### ISSUE THREAD

**Issue by pgolm** [deepmap/oapi-codegen#185]
It is not possible to generate a schema with properties where `null` is a not omitted value.
I would expect that a property with `nullable: true` that `null` is a value so that it will be part of a response.

For example the following schema definition:
```yaml
NullableProperties:
    type: object
    properties:
        optional:
            type: string
            nullable: false
        optionalAndNullable:
            type: string
            nullable: true
        required:
            type: string
            nullable: false
        requiredAndNullable:
            type: string
            nullable: true
```

generates the following type:

```go
type NullableProperties struct {
	Optional            *string `json:"optional,omitempty"`
	OptionalAndNullable *string `json:"optionalAndNullable,omitempty"`
	Required            string  `json:"required"`
	RequiredAndNullable string  `json:"requiredAndNullable"`
}
```

With this type definition, `RequiredAndNullable` couldn't be `null` and `OptionalAndNullable` will be omitted. I would expect a generated type like the following:

```go
type NullableProperties struct {
	Optional            *string `json:"optional,omitempty"`
	OptionalAndNullable *string `json:"optionalAndNullable"`
	Required            string  `json:"required"`
	RequiredAndNullable *string `json:"requiredAndNullable"`
}
```

**Comment by bhingston-va** [comment]
Running into some issues in this area that led me here (however slightly different). I think your schema definition example might be wrong unless I'm misunderstanding "required". Should it not be:
```yaml
NullableProperties:
    type: object
    required:
        - required
        - requiredAndNullable
    properties:
        optional:
            type: string
            nullable: false
        optionalAndNullable:
            type: string
            nullable: true
        required:
            type: string
            nullable: false
        requiredAndNullable:
            type: string
            nullable: true
```
reference https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml
