### ISSUE TITLE
Schema type that maps to string date-time is empty in response.

### ISSUE THREAD

**Issue by manderson23** [deepmap/oapi-codegen#187]
The following schema type
```
components:
  schemas:
    Timestamp:
      type: string
      format: date-time
```
is translated to `type Timestamp time.Time`

However, when this is used in a response it is always empty and the time instance isn't converted to a string.

Editing the generated code for the reponse to replace `ExecTime *Timestamp` with `ExecTime *time.Time` resolves the issue.

It looks like the fact that `Timestamp` is a `time.Time` isn't detected by the timestamp conversion code.
