### ISSUE TITLE
not nil value in Date parameter 

### ISSUE THREAD

**Issue by mr-tron** [deepmap/oapi-codegen#233]
I have parameter 
```
        - name: startDateFrom
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-01-14"
```
I generate model with attribute
```
StartDateFrom *openapi_types.Date `json:"startDateFrom,omitempty"
```
but, if I don't send this parameter in request,  in handler I get this field with zero value. Not nil.
![image](https://user-images.githubusercontent.com/702560/94151491-26011f00-fe83-11ea-853a-23ebdeedf737.png)
