### ISSUE TITLE
Adding custom struct tag for types

### ISSUE THREAD

**Issue by faraonc** [deepmap/oapi-codegen#267]
I tried reading thru the [code](https://github.com/deepmap/oapi-codegen/blob/7f267e9c677db40dab28f06f874187ab6a8e90ad/pkg/codegen/schema.go#L330-L332), but it seems like the only tag generated is of `json` e.g.

```golang
// NewPet defines model for NewPet.
type NewPet struct {

	// Name of the pet
	Name string `json:"name"`

	// Type of the pet
	Tag *string `json:"tag,omitempty"`
}
```

Maybe I missed it, but is there a way to add a tag?
```golang
// NewPet defines model for NewPet.
type NewPet struct {

	// Name of the pet
	Name string `json:"name" db:"name"`

	// Type of the pet
	Tag *string `json:"tag,omitempty" db:"tag`
}
```

**Comment by MarkSpencerTan** [comment]
We would need this feature as well, especially since the newer versions of [echo ](https://github.com/labstack/echo)relies on tags on the structs for its binding logic.

**Comment by Dafaque** [comment]
If someone like me starts looking for how to do this before reading the README:
```
Object:
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            tag1: value1
            tag2: value2
```

**Comment by faraonc** [comment]
cool. it was not available when i filed the issue. closing.

**Comment by renom** [comment]
Hi guys. Is it possible to add a struct tag with a value from `description:` openapi field?

Sample input:
```yaml
phone:
  type: string
  minLength: 1
  description: Phone number
```

Sample output:
```go
type GeneratedStruct struct {
  // Phone Phone number
  Phone string `json:"phone" desc:"Phone number"`
}
```
