### ISSUE TITLE
query parameter codegen doesn't respect OpenAPI parameter style

### ISSUE THREAD

**Issue by v-byte-cpu** [deepmap/oapi-codegen#283]
Consider the following API endpoint:

```  
/collections/documents/search:
    get:
      parameters:
        - name: query_by
          in: query
          description: A list of `string` fields that should be queried
            against. Multiple fields are separated with a comma.
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
```

Expected generated query for array with two elements **a** and **b**:

```
/collections/documents/search?query_by=a,b
```

Actual generated query:

```
/collections/documents/search?query_by=a&query_by=b
```
