### ISSUE TITLE
[feature] allow custom format mapping

### ISSUE THREAD

**Issue by emicklei** [deepmap/oapi-codegen#299]
OpenAPI3: "the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. "

It would be nice if we could specify a mapping to a type for such a custom format. E.g.  when "email" is found, use the custom made Go type "Email"

**Comment by deepmap-marcinr** [comment]
Hmm, interesting. We could do type hints in the config file.

**Comment by stellirin** [comment]
UUID is a great example, we use them everywhere. Actually, we can already generate code that could use `uuid.UUID`:
```yaml
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
        name:
          type: string
      required:
        - id
        - name
```
oapi-codegen correctly generates structs and functions with `uuid.UUID`, and event correctly picks the most relevant import:

```go
import "github.com/gofrs/uuid"

// User defines model for User.
type User struct {
	Id   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}
```

But the `runtime` functions for parsing incoming parameters or generating outgoing parameters currently don't accept this type.

For example, we hit `pkg/runtime/styleparam.go@primitiveToString()` and get back `error="unsupported type uuid.UUID"` because `StyleParamWithLocation()` checks only a few basic types.
