### ISSUE TITLE
Reserved golang keywords in spec cause errors

### ISSUE THREAD

**Issue by stevenvegt** [deepmap/oapi-codegen#30]
I have a `type` parameter in my spec as follows:
```yaml
/animal/{type}:
    get:
      summary: Get an animal by type
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
```

Which resuls in the following server interface:
```golang
type ServerInterface interface {
  GetAnimalByType(ctx echo.Context, type string, params GetAnimalByTypeParams) error
}
```

But as you can see this results in a parameter named `type` which is a reseverd golang keyword.

Perhaps pre/post fixing all param names can prevent these errors.

**Comment by deepmap-marcinr** [comment]
There are many cases where this will happen, so I'm thinking of side-stepping the problem by allowing people to specify the Go variable name explicitly via extended properties. You could do something like:
```
/animal/{type}:
    get:
      summary: Get an animal by type
      parameters:
        - name: type
           x-golang-name: animalType
          in: path
          required: true
          schema:
            type: string
```

which would yield
```
type ServerInterface interface {
  GetAnimalByType(ctx echo.Context, animalType string, params GetAnimalByTypeParams) error
}
```

I'm in the middle of a big project right now, but I'll revisit this sometime soon.
