### ISSUE TITLE
invalid go code generated from YAML containing literal values

### ISSUE THREAD

**Issue by wtask** [deepmap/oapi-codegen#335]
portion of source spec:

```yaml
    response-status-flag:
      title: Response status value
      type: integer
      minimum: 0
      maximum: 1
      description: |
        The value `1` indicates all data objects provided are valid.
        This does not signify a valid project token or secret.
        The value `0` indicates one or more data objects in the body are invalid.
```

generated go code (with errors):

```go
// The value `1` indicates all data objects provided are valid.
This does not signify a valid project token or secret.
The value `0` indicates one or more data objects in the body are invalid.

type ResponseStatusFlag  int

```

oapi-codegen v1.6.0
