### ISSUE TITLE
enums - handling pointer to constant

### ISSUE THREAD

**Issue by RuiLoureiro** [deepmap/oapi-codegen#360]
Suppose I have the following model definition in my api.yaml:
```
components:
  schemas:
    MyModel:
      title: My model
      properties:
        status:
          type: string
          enum:
            - PENDING
            - COMPLETED

```

With the recent enum changes, this will generate the following code:
```
// Defines values for MyModelStatus.
const (
	MyModelStatusCOMPLETED MyModelStatus = "COMPLETED"

	MyModelStatusPENDING MyModelStatus = "PENDING"
)

// MyModel defines model for MyModel.
type MyModel struct {
	Status *MyModelStatus `json:"status,omitempty"`
}

// MyModelStatus defines model for MyModel.Status.
type MyModelStatus string
```

When I need to initialize a struct of type `MyModel`, I would like to do something like:
```
my_model := MyModel{
	Status: &MyModelStatusCOMPLETED,
}
```
Since in go you can't take the address of a const, I have to do something like what's described in [this](https://stackoverflow.com/a/35146856) SO thread:

```
const k = MyModelStatusCOMPLETED
v := k
my_model := MyModel{
	Status: &v
}
```

Is there any workaround that I'm unaware of?
