### ISSUE TITLE
Unclear what AccessTokenScopes is in echo generated server

### ISSUE THREAD

**Issue by mitar** [deepmap/oapi-codegen#371]
In the echo generated server I see code like:

```
ctx.Set(AccessTokenScopes, []string{""})
```

My API spec includes:

```
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer

security:
  - AccessToken: []
```

So I require an access token but no scopes are required.

I could not find any example how to use that. For example, if I use [JWT middleware](https://echo.labstack.com/middleware/jwt/).

Moreover, why is the code `[]string{""}` and not `[]string{}` for empty list?
