### ISSUE TITLE
Creating wrapper objects for query parameters

### ISSUE THREAD

**Issue by shivag46** [deepmap/oapi-codegen#403]
I am using OpenAPI to generate client classes for Go and several other languages. Here is a sample from my yaml file specifying the query parameters required for an endpoint

```
      parameters:
        - name: filter_by
          in: query
          description:
            Filter conditions for refining your documents to delete. Separate
            multiple conditions with &&.
          schema:
            type: string
            example: "num_employees:>100 && country: [USA, UK]"
          required: true
        - name: batch_size
          in: query
          description:
            Batch size parameter controls the number of documents that should be deleted
            at a time. A larger value will speed up deletions, but will impact performance
            of other operations running on the server.
          required: true
          schema:
            type: integer
```

When I run the generator it creates and wraps all these query parameters into a single structure like this

```
type DeleteDocumentsParams struct {

	// Filter conditions for refining your documents to delete. Separate multiple conditions with &&.
	FilterBy string `json:"filter_by"`

	// Batch size parameter controls the number of documents that should be deleted at a time. A larger value will speed up deletions, but will impact performance of other operations running on the server.
	BatchSize int `json:"batch_size"`
}
```

But this was not the case with Swagger or other generators where we need to explicitly wrap the parameters into an object type for the class to be generated. I mean like this

```
parameters:
        - name: deleteQueryParams
          in: query
          schema:
            type: object
            properties:      
              filter_by:
                type: string
                example: "num_employees:>100 && country: [USA, UK]"
              batch_size:
                description:
                  Batch size parameter controls the number of documents that should be deleted
                  at a time. A larger value will speed up deletions, but will impact performance
                  of other operations running on the server.
                type: integer
``` 

Is it possible to disable the default behaviour of the generator to wrap the separate query parameters into an object and do so only when explicitly done in the yaml file?  I need this to ensure uniformity in all client libraries generated across several languages.
