### ISSUE TITLE
Ability to reference existing struct in schema

### ISSUE THREAD

**Issue by jlarfors** [deepmap/oapi-codegen#445]
I haven't been able to find a way to reference existing Go structs in my openapi spec.
This issue was closed, and this might've worked previously, but I was not able to get it working again:
https://github.com/deepmap/oapi-codegen/issues/195

I have some generated structs (from another framework) that I need to use mainly for POST operations. Is there a way to do this?

E.g. if I have a `Project` struct that already exists and i want to use that in the API, this would be quite nice:

```yaml
components:
  schemas:
    Project:
      $ref: "github.com/org/repo/mypackage:Project"
```

**Comment by Karitham** [comment]
You can use the `x-go-type` tag to add an existing type. so for example
```yaml
components:
  schemas:
    PetID:
      x-go-type: testType
    Pet:
      required:
        - id
        - name
      properties:
        id:
          x-go-type: testType
        name:
          type: string
```
will generate
```go
// Pet defines model for Pet.
type Pet struct {
	Id   testType `json:"id"`
	Name string   `json:"name"`
}

// PetID defines model for PetID.
type PetID testType
```

**Comment by deefdragon** [comment]
I am going to put how I imported google's UUID library strutcs in here should anyone in the future needs to reference it. It took me quite a while because the different things that I needed to reference were split among several different issues and documentation locations. I believe that this should work for anything that implements the unmashal re: #404

./uuid.yml
```yml
components:
  schemas:
    UUID:
      x-go-type: uuid.UUID
```

./config.yml
```yml
output:
  openapi.gen.go
package: <packageName>
generate:
  - types
  - server
  - client
import-mapping:
  uuid.yml: github.com/google/uuid
```

./openapi.yml
```yml
...
paths:
  /stuff/{uuidOfSomeKind}:
    post:
      parameters:
        - name: uuidOfSomeKind
          in: path
          description: the UUID 
          required: true
          schema:
            $ref: uuid.yml#/components/schemas/UUID
...
```
