### ISSUE TITLE
OpenAPI property names converted to camel case are not unique

### ISSUE THREAD

**Issue by jake-scott** [deepmap/oapi-codegen#452]
OpenAPI specifies that schema element names are case insensitive.  The conversion to camel case results in name clashes, for example:
```
    test:
          type: object
          properties:
            a:
              type: string
            A:
              type: string
            abc_abc:
              type: string
            abc_Abc:
              type: string
```

results in :
```
// Test defines model for test.
type Test struct {
        A      *string `json:"A,omitempty"`
        A      *string `json:"a,omitempty"`
        AbcAbc *string `json:"abc_Abc,omitempty"`
        AbcAbc *string `json:"abc_abc,omitempty"`
}
```

I propose that the generator (in ToCamelCase())should append an extra '_' to a character when capNext is true and the character being added is already a capital, so we would end up with :
```
// Test defines model for test.
type Test struct {
        A_      *string `json:"A,omitempty"`
        A      *string `json:"a,omitempty"`
        AbcA_bc *string `json:"abc_Abc,omitempty"`
        AbcAbc *string `json:"abc_abc,omitempty"`
}
```
... reasoning being that it is most common to use lower case names in the OpenAPI specification so this would keep the use of the extra '_' chars to a minimum. (this is an assumption, I'm not sure if everyone would agree)
