### ISSUE TITLE
Access custom property in template

### ISSUE THREAD

**Issue by yasir-ss** [deepmap/oapi-codegen#491]
How can I access a custom property in a template, such as echo-register.tmpl? For example, if I have:
```
  /foos:
    get:
      description: Return all foos
      operationId: getFoos
      x-ldapGroup: foo
```

Using ```// {{ .x-ldapGroup }}``` or ```// {{ .xldapGroup }}``` in a template result in an error.
