### ISSUE TITLE
Using per-endpoint middleware

### ISSUE THREAD

**Issue by screwyprof** [deepmap/oapi-codegen#518]
At the moment when `RegisterHandlersWithBaseURL` is generated there is no way to specify per-handler middleware. In our use case we need to use some middleware's on per-handler bases rather than global ones.

The `EchoRouter` interface has a 3rd param to pass on the middleware:
```
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}
```

However there's no way to let `RegisterHandlersWithBaseURL` know about it. Is there any way to do it without having a global middleware which has to check whether it can be run for the given request?

**Comment by valensto** [comment]
Hey @screwyprof there is a started solution in [462](https://github.com/deepmap/oapi-codegen/pull/462#issue-1021609962)

**Comment by screwyprof** [comment]
Hi @valensto. Thanks for letting me know. Are there any plans to support `echo`?

**Comment by festinuz** [comment]
I think #462 is abandoned, i started another take on this issue here: #947

**Comment by jamietanna** [comment]
Apologies for missing this folks.

The proposals in #462 and #947 look like a reasonable solution - at a first glance. I can try and come back to this early next year when I've got a bit more time to review + possibly propose some changes.

Related: https://github.com/getkin/kin-openapi/issues/825

**Comment by daniel-orlov** [comment]
Hi! Was this ever resolved? Ihave the same problem with standard http server (need per endpoint middlewares) and so far  searching through a labyrinth of links between closed issues led me nowhere 😢 

Apologies if it was solved and I am just oblivious.

**Comment by gmr458** [comment]
any update on this?

**Comment by dabdine** [comment]
Could path tags be used for this purpose? e.g.:

```yaml
paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by Status
      tags:
        - pets
      ...
```

Then a `RegisterHandlers` function is generated per group, which in this case would be `pets`. That way you could just tag `authenticated` on it, and you'd get a `RegisterHandlersAuthenticated` function that only contains the paths in that group. In that case, you can just use an echo.Group as a subrouter and pass it to the RegisterHandlersXXX function as is what happens today (the `EchoRouter` the generated function takes is meant to be compatible with `echo.Group` or `echo.echo`). To avoid blowing up generated files, there can be include/excludes in the config.

**Comment by rbnbr** [comment]
Just wanted to drop this into the conversation and hope for feedback/suggestions. Maybe it is helpful to others too.

I just started with OpenAPI and was also looking for this feature since we historically have separate middlewares depending on the set of handlers. 
Regarding the set of features oapi-codegen provides, I, for now, chose to go with the import-mapping feature to implement the desired functionality, see docs [Splitting large OpenAPI specs across multiple packages (aka "Import Mapping" or "external references")](https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#import-mapping).

It is probably neither the best approach to do this (if at all) nor intended to be used like this(?) but it seems compliant with the specs and the current feature set and is fairly simple to do. 
What I am currently doing is to group the set of handlers that use the same middleware in separate packages by assigning each group its own tag, like this:

File structure:
- api.yaml
- common.yaml
- api/
  - common/
     - cfg.yaml
     - generate.go
  - ping1/
     - cfg.yaml
     - generate.go
  - ping2/
     - cfg.yaml
     - generate.go
- main.go

`api.yaml`
````yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: API
  description: .
tags:
  - name: ping
    description: Ping-pong endpoint
paths:
  /ping1:
    get:
      tags:
        - ping1
      responses:
        '200':
          description: pong response
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Pong'
  /ping2:
    get:
      tags:
        - ping2
      responses:
        '200':
          description: pong response
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Pong'
````
 
and both can use the same structs via:

`common.yaml`
````yaml
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
````

`api/common/cfg.yaml`
````yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: common
output: types.gen.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
````

`api/common/generate.go`
````go
package common

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -config cfg.yaml ../../common.yaml
````

`api/ping1/cfg.yaml`
````yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
# ping1/cfg.yaml
package: ping1
output: server.gen.go
generate:
  models: true
  gorilla-server: true
output-options:
  # to make sure that all types are generated
  include-tags: ["ping1"]
import-mapping:
  ./common.yaml: <some_path>/api/common  # adjust project path
````

`api/ping1/generate.go`
````go
package ping1

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -config cfg.yaml ../../api.yaml 
````

`api/ping2/cfg.yaml`
````yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
# ping2/cfg.yaml
package: ping2
output: server.gen.go
generate:
  models: true
  gorilla-server: true
output-options:
  # to make sure that all types are generated
  include-tags: ["ping2"]
import-mapping:
  ./common.yaml: <some_path>/api/common  # adjust project path
````

`api/ping2/generate.go`
````go
package ping2

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -config cfg.yaml ../../api.yaml 
````

Each package then implements its own server interface which I add in the main.go file to the root mux like this:

`main.go`
````go
import (
    // ...
    "<some_path>/api/ping1"
    "<some_path>/api/ping2"
)

func main() {
    // ...
    r := mux.NewRouter()

    // ... potentially adding some global middlewares to r here


    ping1.HandlerWithOptions(ping1.NewServer(), ping1.GorillaServerOptions{
		BaseRouter: r,
		Middlewares: []ping1.MiddlewareFunc{}, // middlewares for all handlers in the ping1 module
	})

    ping2.HandlerWithOptions(ping2.NewServer(), ping2.GorillaServerOptions{
		BaseRouter: r,
		Middlewares: []ping2.MiddlewareFunc{}, // middlewares for all handlers in the ping2 module
	})
}
````

Obviously it is not optimal to actually create a package for each handler if this is really necessary, though, the the import-mapping approach still provides quite some flexibility in this regard.
