### ISSUE TITLE
Incorrect type after binding *time.Type

### ISSUE THREAD

**Issue by lukacsaronzs** [deepmap/oapi-codegen#570]
Hello.
I have the following query param definition:
``` yaml
      parameters:
        - in: query
          name: createdAfter
          schema:
            type: string
            format: date-time
          description: filter users created after the specified datetime
```
This generates the param struct :
```go
type Params struct {
	CreatedAfter *time.Time `json:"createdAfter,omitempty"`
}
```

When I don't send the the `createdAfter` param I expect the value of `params.CreatedAfter` to be equal to `nil`, but actually it is `*time.Time {wall: 0, ext: 0, loc: *time.Location nil}`, a pointer to the "zero-time".
I have seen several discussions about parsing Time and Date objects, but it is still not clear for me if this is the expected behaviour or something that will be fixed in the future.
