### ISSUE TITLE
gin query parameters not being generated

### ISSUE THREAD

**Issue by chase-isabelle-roostify** [deepmap/oapi-codegen#580]
Hey, I tried using this tool to generate a gin service interface, and I notice it fails to generate the `in: query` parameters correctly (or at all).

This is the command I'm using to generate:
```
	docker run -w /workdir -v $(shell pwd):/workdir golang /bin/bash -c '\
		go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest && \
		oapi-codegen -generate gin -package api api/openapi/api.yaml > internal/api/openapi/api.go'
```

Most of the code generates correctly; however, when there is a parameter with the `in: query` property, it seems to fail to generate:
![image](https://user-images.githubusercontent.com/103128589/169444379-516b86c3-eabc-4a02-9ff8-47892ae0f8a0.png)

This is the clip from the yaml:
```
paths:
  /pets:
    get:
      description: |
        Returns all pets from the system that the user has access to
        Nam sed condimentum est. Maecenas tempor sagittis sapien, nec rhoncus sem sagittis sit amet. Aenean at gravida augue, ac iaculis sem. Curabitur odio lorem, ornare eget elementum nec, cursus id lectus. Duis mi turpis, pulvinar ac eros ac, tincidunt varius justo. In hac habitasse platea dictumst. Integer at adipiscing ante, a sagittis ligula. Aenean pharetra tempor ante molestie imperdiet. Vivamus id aliquam diam. Cras quis velit non tortor eleifend sagittis. Praesent at enim pharetra urna volutpat venenatis eget eget mauris. In eleifend fermentum facilisis. Praesent enim enim, gravida ac sodales sed, placerat id erat. Suspendisse lacus dolor, consectetur non augue vel, vehicula interdum libero. Morbi euismod sagittis libero sed lacinia.

        Sed tempus felis lobortis leo pulvinar rutrum. Nam mattis velit nisl, eu condimentum ligula luctus nec. Phasellus semper velit eget aliquet faucibus. In a mattis elit. Phasellus vel urna viverra, condimentum lorem id, rhoncus nibh. Ut pellentesque posuere elementum. Sed a varius odio. Morbi rhoncus ligula libero, vel eleifend nunc tristique vitae. Fusce et sem dui. Aenean nec scelerisque tortor. Fusce malesuada accumsan magna vel tempus. Quisque mollis felis eu dolor tristique, sit amet auctor felis gravida. Sed libero lorem, molestie sed nisl in, accumsan tempor nisi. Fusce sollicitudin massa ut lacinia mattis. Sed vel eleifend lorem. Pellentesque vitae felis pretium, pulvinar elit eu, euismod sapien.
      operationId: findPets
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          style: simple
          schema:
            type: integer
            format: int32
```

When I comment out those parameters, the generated code is fine. This yaml was copied from the petstore example linked on the readme.
