### ISSUE TITLE
x-oapi-codegen-extra-tags ignored when type is array

### ISSUE THREAD

**Issue by artecoop** [deepmap/oapi-codegen#678]
Hello all!

imagine having this component schema

```yaml
NotificationInput:
    type: object
    required:
        - content
    properties:
        id:
            type: string
            description: '(optional when new) Firestore ID for updates'
        frequency:
            type: integer
            description: '(optional) The number of days after the notification should return to the unread state'
        content:
            type: array
            items:
                '$ref': '#/components/schemas/NotificationContent'
            x-oapi-codegen-extra-tags:
                validate: required
                min: 1
```

during code generation, the `x-oapi-codegen-extra-tags` is ignored: here's the code generated

```go
type NotificationInput struct {
    Content []NotificationContent `json:"content"`

    // (optional) The number of days after the notification should return to the unread state
    Frequency *int `json:"frequency,omitempty"`

    // (optional when new) Firestore ID for updates
    Id *string `json:"id,omitempty"`
}
```

but I'd expect to have 
```go
...
Content []NotificationContent `json:"content" validate:"required,min=1"`
...
```

Any help is appreciated
