### ISSUE TITLE
Invalid processing of string format "binary"

### ISSUE THREAD

**Issue by florentchauveau** [deepmap/oapi-codegen#679]
Since the introduction of this commit https://github.com/deepmap/oapi-codegen/commit/2cf7fcf5b26d1a4362e7c300bd65c20f4f6c4298 in master, we cannot send arbitrary data in "binary" string formats:

Here is what happens with this kind of string: `data:bonjours`, with the echo Binder:
```
failed to bind body: code=400, message=illegal base64 data at input byte 4, internal=illegal base64 data at input byte 4
```

It happens because of `UnmarshalJSON` in `types.File`, that attempts to JSON decode the input into a []byte. However, when json decoding into a []byte, Go expects the source to be base64 encoded.

"binary" string format is supposed to be "any sequence of octets", not "base64 encoded data".

The Go behaviour can be seen here: https://go.dev/play/p/uk7iNb8YzAR

**Comment by florentchauveau** [comment]
After further investigation, Go's behaviour is expected with JSON encoding bytes, because JSON doesn't support binary data.

We were mixing `application/json` content type with a `string` format `binary`, like this:

```yaml
application/json:
  schema:
    type: object
    properties:
      firstname:
        type: string
        pattern: \pL
        minLength: 1
        maxLength: 80
        example: John
      profilePicture:
        type: string
        format: binary
        example: data:image/jpeg;base64,Ym9uam91cnM=
```

Which is not a good idea. Either use a binary content-type (like `image/jpeg`) and return just the image with the endpoint, or use format `byte` if you want to embed binary content.

I will close this issue and remove the PR.
