### ISSUE TITLE
Help integrating with Firebase authentication

### ISSUE THREAD

**Issue by artecoop** [deepmap/oapi-codegen#691]
Hello everyone!

I'm trying to integrate my openapi 3 spec with Firebase authentication.

In my .yml file, I specified under components

```yml
components:
    securitySchemes:
        firebase:
            type: 'oauth2'
            flows:
                implicit:
                    authorizationUrl: ''
                    scopes:
                        read: Grants read access
                        write: Grants write access
            x-google-issuer: 'https://securetoken.google.com/PROJECT_ID'
            x-google-jwks_uri: 'https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com'
            x-google-audiences: 'PROJECT_ID'
```

and for example in an endpoint 
```yml
 /api/notifications:
        get:
            summary: Returns all the notifications
            operationId: getAll
            security:
                - firebase: []
```

Here's the main.go file

```go
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"path/filepath"

	"github.com/artecoop/ins/server/src/api"

	firebase "firebase.google.com/go"
	
	oapimiddleware "github.com/deepmap/oapi-codegen/pkg/chi-middleware"
	"github.com/go-chi/chi/v5"
	"google.golang.org/api/option"
	"cloud.google.com/go/firestore"
)

type database struct {
	firestoreClient *firestore.Client
}

func main() {
	swagger, err := api.GetSwagger() 
	if err != nil {
		log.Fatalf("Error loading swagger spec: %v", err)
	}

	serviceAccountKeyFilePath, err := filepath.Abs("../serviceAccountKey.json")
	if err != nil {
		panic("Unable to load serviceAccountKeys.json file")
	}

	opt := option.WithCredentialsFile(serviceAccountKeyFilePath)
	app, err := firebase.NewApp(context.Background(), nil, opt)
	if err != nil {
		log.Fatalf("firebase.NewApp: %v", err)
	}

	client, err := app.Firestore(context.Background())
	if err != nil {
		log.Fatalf("app.Firestore: %v", err)
	}
	defer client.Close()

	firestore := database{client}

	swagger.Servers = nil

	router := chi.NewRouter()
	router.Use(oapimiddleware.OapiRequestValidator(swagger))

	api.HandlerFromMux(Resolver{firestore}, router)

	log.Println("Starting HTTP server on port " + os.Getenv("PORT"))
	http.ListenAndServe(":"+os.Getenv("PORT"), router)
}
```

Note: `Resolver{}` is my implementation to resolve mappings from the codegen.

Every request sent returns `401 Unauthorized`with the error `Security requirements failed`.

Here I'm stuck. There is no documentation about this feature in the repo, so I'm lost. Please help !

**Comment by artecoop** [comment]
Well in the end I've solved using JWT schema

```yml 
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
```

and manually checking the JWT using Firebase auth like this

```go
authClient, err := app.Auth(context.Background())
if err != nil {
    log.Fatalf("Unable to create firebase Auth client")
}

validatorOptions := &oapimiddleware.Options{}

validatorOptions.Options.AuthenticationFunc = func(c context.Context, input *openapi3filter.AuthenticationInput) error {
	authHdr := input.RequestValidationInput.Request.Header.Get("Authorization")
	if authHdr == "" {
		return errors.New("auth-header-missing")
	}
	if !strings.HasPrefix(authHdr, "Bearer ") {
		return errors.New("auth-header-malformed")
	}

	_, err := authClient.VerifyIDToken(c, authHdr[7:])
	if err != nil {
		return errors.New("unable-to-verify-jwt")
	}

	return nil
}
```
