### ISSUE TITLE
Additional `True` and `False` field generated 

### ISSUE THREAD

**Issue by mirzakhany** [deepmap/oapi-codegen#702]
Hi, I tried flowing object in my open api definition, which as you see doesn't contain True, False fields, but they appear in the generated code:

``` yaml
    JSONWebKey:
      type: object
      required:
        - alg
        - kid
        - use
        - kty
        - x5c
      properties:
        alg:
          type: string
        crv:
          type: string
        d:
          type: string
        dp:
          type: string
        dq:
          type: string
        e:
          type: string
        k:
          type: string
        kid:
          type: string
        kty:
          type: string
        n:
          type: string
        p:
          type: string
        q:
          type: string
        qi:
          type: string
        use:
          type: string
        x:
          type: string
        x5c:
          type: array
          items:
            type: string
        y:
          type: string
```

and generated code:

``` go
// JSONWebKey defines model for JSONWebKey.
type JSONWebKey struct {
	Alg   string   `json:"alg"`
	Crv   *string  `json:"crv,omitempty"`
	D     *string  `json:"d,omitempty"`
	Dp    *string  `json:"dp,omitempty"`
	Dq    *string  `json:"dq,omitempty"`
	E     *string  `json:"e,omitempty"`
	False *string  `json:"false,omitempty"`   // <----------- 
	K     *string  `json:"k,omitempty"`
	Kid   string   `json:"kid"`
	Kty   string   `json:"kty"`
	P     *string  `json:"p,omitempty"`
	Q     *string  `json:"q,omitempty"`
	Qi    *string  `json:"qi,omitempty"`
	True  *string  `json:"true,omitempty"` // <----------- 
	Use   string   `json:"use"`
	X     *string  `json:"x,omitempty"`
	X5c   []string `json:"x5c"`
}
```
Im using the latest version from master branch with flowing config file:

```yaml
package: api
generate:
  chi-server: true
  models: true
output: ./openapi.gen.go
produces:
  - application/json
```
