### ISSUE TITLE
Enums with single values cause "is not a type" error

### ISSUE THREAD

**Issue by saulhoward** [deepmap/oapi-codegen#703]
Create an enum schema with a single value:

```yaml
    Animal:
      enum:
        - Dog
      type: string
```

Generate a client and try to compile the code, get the error:

```bash
api/types.gen.go:333:27: AnimalDog (constant "Dog" of type Animal) is not a type
```
I assume this is because oapi-codegen collapses a single-value enum to a string constant.

Now add a second value:

```yaml
    Animal:
      enum:
        - Dog
        - Dummy
      type: string
```

And the client compiles.

I think enums with a single value are valid, and should be treated the same way as enums with multiple values.

**Comment by saulhoward** [comment]
This is wrong sorry. The actual cause was that I has two types:

```
Animal:
  enum:
     - Dog
  type: string
AnimalDog:
  enum:
    - Dog
   type: string
```

And the generated code was in conflict.  Not sure if there's a better solution here.

Maybe you could search for conflicts when generating names.
