### ISSUE TITLE
`x-go-type-import` ignored unless property of object

### ISSUE THREAD

**Issue by deefdragon** [deepmap/oapi-codegen#760]
I use google's UUID quite a bit in my code. The adition of x-go-type-import made that trivial to use in API generation, unfortunatly, sometimes the generation imports the gofrs/uuid package instead, and I believe I have narrowed down why.

Of the following three cases, only the `Schema property` one imported the google variant. 
## Schema direct type
```yaml
#...
compoents:
  schemas:
    UUID:
      type: string
      x-go-type: uuid.UUID
      x-go-type-import:
        name: uuid
        path: github.com/google/uuid
```
## Schema property
```yaml
#...
compoents:
  schemas:
    foo:
      type: object
      properties:
        bat:
          type: string
          x-go-type: uuid.UUID
          x-go-type-import:
            name: uuid
            path: github.com/google/uuid
```
## Path Paremeter
```yaml
#...
      parameters:
        - name: webhook
          in: path
          description: The ID of the webhook that is being called.
          required: true
          schema:
            type: string
            x-go-type: uuid.UUID
            x-go-type-import:
              name: uuid
              path: github.com/google/uuid
```
