### ISSUE TITLE
oapi-codegen happily generates bad openAPI schema that has duplicated fields

### ISSUE THREAD

**Issue by nathani-axis** [deepmap/oapi-codegen#798]
Let me know if this is not in the scope of this project, I assumed it would be but I understand if it's not.

While I was working I had some mistake in my openAPI schema at some point, and the yaml was invalid. oapi-codegen happily generated code for it though, without any errors. This doesn't sound like good behaviour, and I would assume that if fed bad input, oapi-codegen should reject it and error.

example openAPI schema:
```yml
...

components:
  schemas:
    foo:
      type: string
    foo:
      type: string
```

my yaml language server complained, but the generation worked "without issues".
