### ISSUE TITLE
error parsing configuration style as old version or new version: <nil>

### ISSUE THREAD

**Issue by Southclaws** [deepmap/oapi-codegen#831]
Hey, I just updated from `v1.11.1-0.20220906181851-9c600dddea33` (can't remember why we had our version locked to this) to `v1.12.1` and when trying to generate code, I get this error message without any details:

```
error parsing configuration style as old version or new version: <nil>
```

The config is:

```
package: openapi
output: ./openapi/generated_server.go
generate:
  client: true
  server: true
  echo-server: true
  strict-server: true
  models: true
  embedded-spec: true
```

Which seems to line up with the examples and readme. Is this version not ready to use yet?
