### ISSUE TITLE
1.12.2 type generation doesn't apply to top level schema

### ISSUE THREAD

**Issue by goshlanguage** [deepmap/oapi-codegen#862]
Hey team,

First thanks a ton, this project is extremely helpful to quickly start and iterate on apis in go.

I am trying to use the `x-go-type` extension for a top level schema like so:

```
components:
  schemas:
    UpstreamObject:
      x-go-type: upstream.Object
      x-go-type-import:
        name: upstream
        path: github.com/upstream/thisisntarealrepo/pkg/fake
```

When I run `oapi-codegen`, the imports aren't generated, nor are the types referenced in this way. I understand that the extension is targeted at fields, and in this way the object is modeled appropriately, but I'd rather skip generation and provide `oapi-codegen` with the type to use when this Object type is referenced.

Is there a way to do this that I'm overlooking, or would a PR for this be welcomed? If so, any ideas on where to start?
Thanks!
