### ISSUE TITLE
Bug: array with enum doesn't add quotes around enums

### ISSUE THREAD

**Issue by kotyara85** [deepmap/oapi-codegen#900]
Version: v1.12.4

```
        grant_types:
          type: array
          enum: ["client_credentials", "authorization_code", "refresh_token"]
```

results into broken golang code -
```
	AuthorizationCode ClientRequestGrantTypes = authorization_code
	ClientCredentials ClientRequestGrantTypes = client_credentials
	RefreshToken      ClientRequestGrantTypes = refresh_token
```

I'd expect quotes to be added.
string type works just fine

**Comment by jeffgran-dox** [comment]
similarly, an empty string as an option of an enum generates invalid go code:
```
"schema": {
  "type": "string",
  "format": "date-time",
  "nullable": true,
  "enum": [
    "",
    1,
    2,
    3,
    4,
    5,
    6,
    7
  ]
}
```

results in:

```
// Defines values for FindingsListParamsCreated.
const (

  FindingsListParamsCreatedEmpty FindingsListParamsCreated = 
  FindingsListParamsCreatedN1 FindingsListParamsCreated = 1
  FindingsListParamsCreatedN2 FindingsListParamsCreated = 2
  FindingsListParamsCreatedN3 FindingsListParamsCreated = 3
  FindingsListParamsCreatedN4 FindingsListParamsCreated = 4
  FindingsListParamsCreatedN5 FindingsListParamsCreated = 5
  FindingsListParamsCreatedN6 FindingsListParamsCreated = 6
  FindingsListParamsCreatedN7 FindingsListParamsCreated = 7
)
```

**Comment by timo-klarshift** [comment]
I am having a similar issue:

```yaml
parameters:
        - description: Filter information returned
          explode: false
          in: query
          name: only
          schema:
            enum:
              - build
              - system
              - config
              - status
            items:
              type: string
            type: array
          style: form
```

```go
const (
	Build  X = build
	Config X = config
	Status X = status
	System X = system
)
```

**Comment by mromaszewicz** [comment]
This is a comment from an automated bug scrub, after making a significant number of fixes to the code generation.

We reproduced this against the current `main` and the broken (unquoted) constants are now correctly quoted.

**Spec used** (`spec.yaml`) — the array's `enum` belongs on its `items`:
```yaml
openapi: "3.0.3"
info:
  title: Test array enum
  version: "1.0"
paths:
  /clients:
    post:
      operationId: createClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        "201": { description: created }
components:
  schemas:
    ClientRequest:
      type: object
      properties:
        grant_types:
          type: array
          items:
            type: string
            enum: ["client_credentials", "authorization_code", "refresh_token"]
```

**Config used** (`config.yaml`):
```yaml
package: repro
output: types.gen.go
generate:
  models: true
```

**Result:** the generated enum constants are now properly quoted string literals (and the code compiles — verified with `go build` against the current runtime):
```go
const (
	AuthorizationCode ClientRequestGrantTypes = "authorization_code"
	ClientCredentials ClientRequestGrantTypes = "client_credentials"
	RefreshToken      ClientRequestGrantTypes = "refresh_token"
)
```
Closing as fixed.
