### ISSUE TITLE
Load user-templates from URL

### ISSUE THREAD

**Issue by deefdragon** [deepmap/oapi-codegen#905]
I have a number of smaller services that I generate API for (ideally) using the same custom user templates, all in different repositories. To prevent drift between my customized templates in different services, I would like to be able to set the template with a URL as opposed to the raw template file.

Example:
```yaml
output: api.gen.go
package: api
output-options:
  skip-prune: true
  user-templates:
    client-with-responses.tmpl: https://raw.githubusercontent.com/deefdragon/oapi-templates/main/templates/client-with-responses.tmpl
```
