### ISSUE TITLE
Using enums with UUID generates invalid code

### ISSUE THREAD

**Issue by cassioconti** [deepmap/oapi-codegen#978]
If I use this `spec.yaml`:

```yaml
components:
  parameters:
    ImporterId:
      name: importerId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        enum:
          - d47a97f5-080b-4984-a49c-dfcff528c6f8
```

And try to generate the types from it with the command:

```sh
oapi-codegen -generate types,skip-prune -package mypkg spec.yaml
```

This is what is generated:

```golang
error generating code: error formatting Go code // Package mypkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package mypkg

import (
        "bytes"
        "compress/gzip"
        "context"
        "encoding/base64"
        "encoding/json"
        "encoding/xml"
        "errors"
        "fmt"
        "gopkg.in/yaml.v2"
        "io"
        "os"
        "net/http"
        "net/url"
        "path"
        "strings"
        "time"

        "github.com/deepmap/oapi-codegen/pkg/runtime"
        openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
        "github.com/getkin/kin-openapi/openapi3"
        "github.com/go-chi/chi/v5"
        "github.com/labstack/echo/v4"
        "github.com/gin-gonic/gin"
        "github.com/gorilla/mux"
)

// Defines values for ImporterId.
const (
  D47a97f5080b4984A49cDfcff528c6f8 ImporterId = d47a97f5-080b-4984-a49c-dfcff528c6f8
)

// ImporterId defines model for ImporterId.
type ImporterId  openapi_types.UUID

: mypkg.go:39:59: invalid digit '8' in octal literal (and 2 more errors)
```

Note that the constant value is invalid.
