### ISSUE TITLE
generate types produces empty go file

### ISSUE THREAD

**Issue by kotyara85** [deepmap/oapi-codegen#985]
```
components:
  schemas:
    ObjectB:
      properties:
        name:
          type: string
```

```
$ oapi-codegen -generate types spec.yaml
// Package Spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.0 DO NOT EDIT.
package Spec
```

Anything I missing?
